### ISSUE TITLE
Add support for arm64

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [CHPC-UofU/container-centos7-ansible#2]
Add support for `arm64`. For example:

```yaml
- name: Set up QEMU
  uses: docker/setup-qemu-action@v2
  with:
  platforms: 'arm64'

- name: Set up Buildx
  uses: docker/setup-buildx-action@v2

- name: Release image
  uses: docker/build-push-action@v4
  with:
    ...
    platforms: linux/amd64,linux/arm64
```
